### PR TITLE
Feature/index and search courses

### PR DESCRIPTION
**Pull request by yoavz1997**
Refers to issue #6

### CODE REVIEW

**Comment by matanpugach** [comment]
@yoavz1997 @saifun please fix the warnings

**Comment by yoavz1997** [comment]
> @yoavz1997 @saifun please fix the warnings

Which warnings?
There were some in other files, but I didn't want to commit other people's files

**Comment by matanpugach** [comment]
@yoavz1997  
image

**Comment by yoavz1997** [comment]
I'm not seeing them in my eclipse.
Are you using Java 8? (We reverted due to the Azure function)

**Pull request merged**
